### PR TITLE
Updated docs to correct version on nuget

### PR DESCRIPTION
**Pull request by Blanen**

### CODE REVIEW

**Comment by ahmad-moussawi** [comment]
Hi actually the current version is 1.0.0-beta527 could you please update your pull request

**Comment by Blanen** [comment]
@ahmad-moussawi Nuget still states it's 484 though ` Latest version: 1.0.0-beta-484 ` on both the base and the execution packages. https://www.nuget.org/packages?q=SqlKata

**Comment by ahmad-moussawi** [comment]
yes the latest version is published on MyGet and not on NuGet, We will publish a new version on NuGet once fixing some pending issues, and the docs currently mention that you have to use the MyGet feed

**Comment by Blanen** [comment]
@ahmad-moussawi Alright, I see. I'll update it. Also found some other places to change it.

**Pull request closed without merging**
